In [1]:
import numpy as np

In [2]:
u_hat = np.array([3, 4, 5])
u_hat = u_hat/np.linalg.norm(u_hat)

In [3]:
b_hat = np.array([6, 7, 8])
b_hat = b_hat/np.linalg.norm(b_hat)

In [4]:
R = np.zeros((3, 3))

R[:,0] = np.cross(b_hat, u_hat)
R[:,1] = np.cross(u_hat, np.cross(b_hat, u_hat))
R[:,2] = u_hat

R[:,0] /= np.linalg.norm(R[:,0])
R[:,1] /= np.linalg.norm(R[:,1])
R[:,2] /= np.linalg.norm(R[:,2])

In [5]:
cos_theta = (np.trace(R)-1)/2

In [6]:
cos_theta

0.11541256274416711

In [7]:
u_x_2 = (R[0,0]-cos_theta)/(1-cos_theta)
u_y_2 = (R[1,1]-cos_theta)/(1-cos_theta)

In [8]:
u_x_2

0.331042150709409

In [9]:
u_y_2

6.499198534360994e-05

In [10]:
u_x_arr = np.array([-np.sqrt(u_x_2), np.sqrt(u_x_2)])
u_y_arr = np.array([-np.sqrt(u_y_2), np.sqrt(u_y_2)])
u_z_arr = np.array([-np.sqrt(1-u_x_2-u_y_2), np.sqrt(1-u_x_2-u_y_2)])

In [11]:
u_x_arr

array([-0.57536263,  0.57536263])

In [12]:
u_y_arr

array([-0.00806176,  0.00806176])

In [13]:
u_z_arr

array([-0.8178587,  0.8178587])

In [14]:
sin_theta_arr_1 = []

for u_x in u_x_arr:
    for u_y in u_y_arr:
        for u_z in u_z_arr:
            sin_theta = (u_x*u_y*(1-cos_theta)-R[0,1])/u_z
            sin_theta_arr_1.append(sin_theta)
            
sin_theta_arr_1 = np.array(sin_theta_arr_1)

In [15]:
sin_theta_arr_1

array([ 0.98328388, -0.98328388,  0.99331764, -0.99331764,  0.99331764,
       -0.99331764,  0.98328388, -0.98328388])

In [16]:
sin_theta_arr_2 = []

for u_x in u_x_arr:
    for u_y in u_y_arr:
        for u_z in u_z_arr:
            sin_theta = (R[1,0]-u_x*u_y*(1-cos_theta))/u_z
            sin_theta_arr_2.append(sin_theta)
            
sin_theta_arr_2 = np.array(sin_theta_arr_2)

In [17]:
sin_theta_arr_2

array([ 1.00335141, -1.00335141,  0.99331764, -0.99331764,  0.99331764,
       -0.99331764,  1.00335141, -1.00335141])

In [18]:
sin_theta_arr = np.unique(np.concatenate((sin_theta_arr_1, sin_theta_arr_2)))

In [19]:
sin_theta_arr

array([-1.00335141, -0.99331764, -0.99331764, -0.98328388,  0.98328388,
        0.99331764,  0.99331764,  1.00335141])

In [20]:
sin_theta = sin_theta_arr[np.argmin(np.abs(sin_theta_arr**2+cos_theta**2-1))]

In [21]:
sin_theta_arr_new = np.array([-np.abs(sin_theta), np.abs(sin_theta)])

In [22]:
sin_theta_arr_new**2 + cos_theta**2

array([1., 1.])

In [23]:
R_arr = []
solutions_arr = []

In [24]:
for u_x in u_x_arr:
    for u_y in u_y_arr:
        for u_z in u_z_arr:
            for sin_theta in sin_theta_arr_new:
                solutions_arr.append([u_x, u_y, u_z, sin_theta])
                R_arr.append([[cos_theta+u_x**2*(1-cos_theta), u_x*u_y*(1-cos_theta)-u_z*sin_theta, u_x*u_z*(1-cos_theta)+u_y*sin_theta],
                             [u_y*u_x*(1-cos_theta)+u_z*sin_theta, cos_theta+u_y**2*(1-cos_theta), u_y*u_z*(1-cos_theta)-u_x*sin_theta],
                             [u_z*u_x*(1-cos_theta)-u_y*sin_theta, u_z*u_y*(1-cos_theta)+u_x*sin_theta, cos_theta+u_z**2*(1-cos_theta)]])

In [25]:
R_arr = np.array(R_arr)
solutions_arr = np.array(solutions_arr)

In [26]:
R_new = R_arr[np.argmin(np.abs(np.linalg.det(R_arr-R)))]
solution = solutions_arr[np.argmin(np.abs(np.linalg.det(R_arr-R)))]

In [27]:
solution

array([-0.57536263,  0.00806176, -0.8178587 ,  0.99331764])

In [28]:
R_new

array([[ 0.40824829,  0.80829038,  0.42426407],
       [-0.81649658,  0.11547005,  0.56568542],
       [ 0.40824829, -0.57735027,  0.70710678]])

In [29]:
R

array([[ 0.40824829,  0.80829038,  0.42426407],
       [-0.81649658,  0.11547005,  0.56568542],
       [ 0.40824829, -0.57735027,  0.70710678]])

In [30]:
u_x_sol = solution[0]
u_y_sol = solution[1]
u_z_sol = solution[2]
sin_theta_sol = solution[3]
cos_theta_sol = cos_theta

In [31]:
if(cos_theta_sol>0 and sin_theta_sol>0):
    theta_sol = np.arcsin(sin_theta_sol)
    
elif(cos_theta_sol<0 and sin_theta_sol>0):
    theta_sol = np.arccos(cos_theta_sol)
    
elif(cos_theta_sol<0 and sin_theta_sol<0):
    theta_sol = 2*np.pi-np.arccos(cos_theta_sol)
    
else:
    theta_sol = 2*np.pi+np.arcsin(sin_theta_sol)

In [32]:
u_x_sol, u_y_sol, u_z_sol, theta_sol

(-0.5753626254019364,
 0.008061760685086723,
 -0.8178587025307289,
 1.4551259989544452)

In [33]:
R_sol = np.array([[np.cos(theta_sol)+u_x_sol**2*(1-np.cos(theta_sol)), u_x_sol*u_y_sol*(1-np.cos(theta_sol))-u_z_sol*np.sin(theta_sol), u_x_sol*u_z_sol*(1-np.cos(theta_sol))+u_y_sol*np.sin(theta_sol)],
                  [u_y_sol*u_x_sol*(1-np.cos(theta_sol))+u_z_sol*np.sin(theta_sol), np.cos(theta_sol)+u_y_sol**2*(1-np.cos(theta_sol)), u_y_sol*u_z_sol*(1-np.cos(theta_sol))-u_x_sol*np.sin(theta_sol)],
                  [u_z_sol*u_x_sol*(1-np.cos(theta_sol))-u_y_sol*np.sin(theta_sol), u_z_sol*u_y_sol*(1-np.cos(theta_sol))+u_x_sol*np.sin(theta_sol), np.cos(theta_sol)+u_z_sol**2*(1-np.cos(theta_sol))]])

In [34]:
R_sol-R

array([[ 5.82867088e-15,  0.00000000e+00, -6.21724894e-15],
       [ 2.10942375e-15,  8.70137296e-15,  9.99200722e-16],
       [-2.10942375e-15,  2.10942375e-15,  2.66453526e-15]])